ui/config/routes.rb
OpenWMS::Application.routes.draw do

  resources :maintorders

  resources :proced_measurements

  resources :asset_proceds

  resources :proceds

  resources :service

  resources :work_task_time_schedules

  resources :work_task_names

  resources :work_task_material_items

  resources :work_task_crews

  resources :work_task_assets

  resources :work_tasks

  resources :work_position_points

  resources :work_order_work_tasks

  resources :work_order_schedules

  resources :work_order_organizations

  resources :work_order_names

  resources :work_order_location_object_refs

  resources :work_order_hazards

  resources :work_order_comments

  resources :work_order_attachments

  resources :work_orders

  resources :vendor_role_types

  resources :vendor_roles

  resources :time_schedules

  resources :seqs

  resources :resultcodes

  resources :requests

  resources :proxy_interfaces

  resources :procedure_measurements

  resources :procedures

  resources :phones

  resources :packages_vendor_role_types

  resources :packages

  resources :other_contactinfos

  resources :organization_names

  resources :organizations

  resources :objectrefs

  resources :nametypes

  resources :name_type_authorities

  resources :measurements

  resources :material_item_names

  resources :material_items

  resources :interfaces

  resources :hazards

  resources :eprilogs

  resources :emails

  resources :districts

  resources :crew_names

  resources :crews

  resources :contactperson_phones

  resources :contactperson_other_contactinfos

  resources :contactperson_emails

  resources :contactperson_addresses

  resources :contactpeople

  resources :comments

  resources :attachments

  resources :asset_procedures

  resources :asset_names

  resources :assets

  resources :address_position_points

  resources :address_hazards

  resources :address_districts

  resources :addresses

  get "home/index"
  get "home/acceptTerms"
  get "home/hideWorkHelp"
  root :to => "home#splash"

  
  

end

ui/app/models/address.rb
class Address < ActiveRecord::Base

   self.table_name = "address"

  has_and_belongs_to_many  :contactpeople, join_table: "contactperson_addresses"

end

ui/app/models/asset.rb
class Asset < ActiveRecord::Base
  self.table_name = "asset"

  belongs_to :address

  has_and_belongs_to_many  :work_tasks, join_table: "work_task_assets"
  has_and_belongs_to_many  :crews, join_table: "crew_assets"
  has_and_belongs_to_many  :proceds, join_table: "asset_proceds"
  
  has_many   :asset_names


end

ui/app/models/asset_name.rb
class AssetName < ActiveRecord::Base
  belongs_to :asset
  belongs_to :asset_name_type, foreign_key: "name_type_id"
end

ui/app/models/attachment.rb
class Attachment < ActiveRecord::Base

  self.table_name = "attachment"

  has_and_belongs_to_many  :work_orders, join_table: "work_order_attachments"

  # Attachment.inheritance_column
  # http://apidock.com/rails/ActiveRecord/Base/inheritance_column/class
  self.inheritance_column = 'none'
  def attachment
    nil
  end

  def poster_filename
    "#{filename}"
  end

end

ui/app/models/comment.rb
class Comment < ActiveRecord::Base

  self.table_name = "comment"

  has_and_belongs_to_many  :work_orders, join_table: "work_order_comments"
end

ui/app/models/crew.rb
class Crew < ActiveRecord::Base

  self.table_name = "crew"

  has_and_belongs_to_many  :work_tasks, join_table: "work_task_crews"
  has_many :crew_names
  has_and_belongs_to_many  :assets, join_table: "crew_assets"


end

ui/app/models/crew_name.rb
class CrewName < ActiveRecord::Base
  self.table_name = "crew_names"

  belongs_to :crew
  belongs_to :crew_name_type, foreign_key:  "name_type_id"

end

ui/app/models/district.rb
class District < ActiveRecord::Base
end

ui/app/models/email.rb
class Email < ActiveRecord::Base

 self.table_name = "email"

 has_and_belongs_to_many  :contactperson, join_table: "contactperson_emails"

end

ui/app/models/eprilog.rb
class Eprilog < ActiveRecord::Base
end

ui/app/models/hazard.rb
class Hazard < ActiveRecord::Base

  self.table_name = "hazards"

  has_and_belongs_to_many  :work_orders, join_table: "work_order_hazards"

end

ui/app/models/interface.rb
class Interface < ActiveRecord::Base
  belongs_to :package
  belongs_to :vendor_role_type
end

ui/app/models/maintorder.rb
class Maintorder < ActiveRecord::Base
  self.table_name = "maintorder"

  has_many :maintorder_names
  has_many :work_orders
end

ui/app/models/nametype.rb
class Nametype < ActiveRecord::Base

  self.table_name = "nametype"


  belongs_to :name_type_authority
end

ui/app/models/objectref.rb
class Objectref < ActiveRecord::Base
end

ui/app/models/package.rb
class Package < ActiveRecord::Base
end

ui/app/models/phone.rb
class Phone < ActiveRecord::Base

  self.table_name = "phone"


 has_and_belongs_to_many  :contactperson, join_table: "contactperson_phones"

end

ui/app/models/proced.rb
class Proced < ActiveRecord::Base
   self.table_name = "proced"

  has_and_belongs_to_many  :assets, join_table: "asset_proceds"
  has_and_belongs_to_many  :measurements, join_table: "proced_measurements"


end

ui/app/models/request.rb
class Request < ActiveRecord::Base
end

ui/app/models/seq.rb
class Seq < ActiveRecord::Base
end

ui/app/models/work_task.rb
class WorkTask < ActiveRecord::Base
  self.table_name = "work_task"

  belongs_to :asset, class_name: "Asset", foreign_key: "old_asset_id"

  has_many :work_task_names
  has_and_belongs_to_many  :work_orders, join_table: "work_order_work_tasks"
  has_and_belongs_to_many  :time_schedules, join_table: "work_task_time_schedules"
  has_and_belongs_to_many  :assets, join_table: "work_task_assets"

  has_and_belongs_to_many  :crews, join_table: "work_task_crews"


end

ui/app/controllers/eprilogs_controller.rb
class EprilogsController < ApplicationController
  before_action :set_eprilog, only: [:show, :edit, :update, :destroy]

  # GET /eprilogs
  # GET /eprilogs.json
  def index
    @eprilogs = Eprilog.all
  end

  # GET /eprilogs/1
  # GET /eprilogs/1.json
  def show
  end

  # GET /eprilogs/new
  def new
    @eprilog = Eprilog.new
  end

  # GET /eprilogs/1/edit
  def edit
  end

  # POST /eprilogs
  # POST /eprilogs.json
  def create
    @eprilog = Eprilog.new(eprilog_params)

    respond_to do |format|
      if @eprilog.save
        format.html { redirect_to @eprilog, notice: 'Eprilog was successfully created.' }
        format.json { render :show, status: :created, location: @eprilog }
      else
        format.html { render :new }
        format.json { render json: @eprilog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eprilogs/1
  # PATCH/PUT /eprilogs/1.json
  def update
    respond_to do |format|
      if @eprilog.update(eprilog_params)
        format.html { redirect_to @eprilog, notice: 'Eprilog was successfully updated.' }
        format.json { render :show, status: :ok, location: @eprilog }
      else
        format.html { render :edit }
        format.json { render json: @eprilog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eprilogs/1
  # DELETE /eprilogs/1.json
  def destroy
    @eprilog.destroy
    respond_to do |format|
      format.html { redirect_to eprilogs_url, notice: 'Eprilog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eprilog
      @eprilog = Eprilog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def eprilog_params
      params.require(:eprilog).permit(:address, :contentType, :create_date, :data, :encoding, :faultCode, :header, :httpMethod, :message, :messageId, :operation, :payload, :responseCode, :resultCode, :INTERFACE_ID, :stage)
    end
end

ui/app/helpers/eprilogs_helper.rb
module EprilogsHelper
end

ui/app/views/eprilogs/_form.html.erb
<%= form_for(@eprilog) do |f| %>
  <% if @eprilog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eprilog.errors.count, "error") %> prohibited this eprilog from being saved:</h2>

      <ul>
      <% @eprilog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :contentType %><br>
    <%= f.text_field :contentType %>
  </div>
  <div class="field">
    <%= f.label :create_date %><br>
    <%= f.datetime_select :create_date %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data %>
  </div>
  <div class="field">
    <%= f.label :encoding %><br>
    <%= f.text_field :encoding %>
  </div>
  <div class="field">
    <%= f.label :faultCode %><br>
    <%= f.text_area :faultCode %>
  </div>
  <div class="field">
    <%= f.label :header %><br>
    <%= f.text_area :header %>
  </div>
  <div class="field">
    <%= f.label :httpMethod %><br>
    <%= f.text_area :httpMethod %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :messageId %><br>
    <%= f.text_field :messageId %>
  </div>
  <div class="field">
    <%= f.label :operation %><br>
    <%= f.text_field :operation %>
  </div>
  <div class="field">
    <%= f.label :payload %><br>
    <%= f.text_area :payload %>
  </div>
  <div class="field">
    <%= f.label :responseCode %><br>
    <%= f.text_area :responseCode %>
  </div>
  <div class="field">
    <%= f.label :resultCode %><br>
    <%= f.text_field :resultCode %>
  </div>
  <div class="field">
    <%= f.label :INTERFACE_ID %><br>
    <%= f.number_field :INTERFACE_ID %>
  </div>
  <div class="field">
    <%= f.label :stage %><br>
    <%= f.text_field :stage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ui/app/views/eprilogs/edit.html.erb
<h1>Editing eprilog</h1>

<%= render 'form' %>

<%= link_to 'Show', @eprilog %> |
<%= link_to 'Back', eprilogs_path %>

ui/app/views/eprilogs/index.html.erb
<h1>Listing eprilogs</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Contenttype</th>
      <th>Create date</th>
      <th>Data</th>
      <th>Encoding</th>
      <th>Faultcode</th>
      <th>Header</th>
      <th>Httpmethod</th>
      <th>Message</th>
      <th>Messageid</th>
      <th>Operation</th>
      <th>Payload</th>
      <th>Responsecode</th>
      <th>Resultcode</th>
      <th>Interface id</th>
      <th>Stage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eprilogs.each do |eprilog| %>
      <tr>
        <td><%= eprilog.address %></td>
        <td><%= eprilog.contentType %></td>
        <td><%= eprilog.create_date %></td>
        <td><%= eprilog.data %></td>
        <td><%= eprilog.encoding %></td>
        <td><%= eprilog.faultCode %></td>
        <td><%= eprilog.header %></td>
        <td><%= eprilog.httpMethod %></td>
        <td><%= eprilog.message %></td>
        <td><%= eprilog.messageId %></td>
        <td><%= eprilog.operation %></td>
        <td><%= eprilog.payload %></td>
        <td><%= eprilog.responseCode %></td>
        <td><%= eprilog.resultCode %></td>
        <td><%= eprilog.INTERFACE_ID %></td>
        <td><%= eprilog.stage %></td>
        <td><%= link_to 'Show', eprilog %></td>
        <td><%= link_to 'Edit', edit_eprilog_path(eprilog) %></td>
        <td><%= link_to 'Destroy', eprilog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Eprilog', new_eprilog_path %>

ui/app/views/eprilogs/new.html.erb
<h1>New eprilog</h1>

<%= render 'form' %>

<%= link_to 'Back', eprilogs_path %>

ui/app/views/eprilogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @eprilog.address %>
</p>

<p>
  <strong>Contenttype:</strong>
  <%= @eprilog.contentType %>
</p>

<p>
  <strong>Create date:</strong>
  <%= @eprilog.create_date %>
</p>

<p>
  <strong>Data:</strong>
  <%= @eprilog.data %>
</p>

<p>
  <strong>Encoding:</strong>
  <%= @eprilog.encoding %>
</p>

<p>
  <strong>Faultcode:</strong>
  <%= @eprilog.faultCode %>
</p>

<p>
  <strong>Header:</strong>
  <%= @eprilog.header %>
</p>

<p>
  <strong>Httpmethod:</strong>
  <%= @eprilog.httpMethod %>
</p>

<p>
  <strong>Message:</strong>
  <%= @eprilog.message %>
</p>

<p>
  <strong>Messageid:</strong>
  <%= @eprilog.messageId %>
</p>

<p>
  <strong>Operation:</strong>
  <%= @eprilog.operation %>
</p>

<p>
  <strong>Payload:</strong>
  <%= @eprilog.payload %>
</p>

<p>
  <strong>Responsecode:</strong>
  <%= @eprilog.responseCode %>
</p>

<p>
  <strong>Resultcode:</strong>
  <%= @eprilog.resultCode %>
</p>

<p>
  <strong>Interface id:</strong>
  <%= @eprilog.INTERFACE_ID %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @eprilog.stage %>
</p>

<%= link_to 'Edit', edit_eprilog_path(@eprilog) %> |
<%= link_to 'Back', eprilogs_path %>