ui/config/routes.rb
OpenWMS::Application.routes.draw do

  resources :maintorders

  resources :proced_measurements

  resources :asset_proceds

  resources :proceds

  resources :service

  resources :work_task_time_schedules

  resources :work_task_names

  resources :work_task_material_items

  resources :work_task_crews

  resources :work_task_assets

  resources :work_tasks

  resources :work_position_points

  resources :work_order_work_tasks

  resources :work_order_schedules

  resources :work_order_organizations

  resources :work_order_names

  resources :work_order_location_object_refs

  resources :work_order_hazards

  resources :work_order_comments

  resources :work_order_attachments

  resources :work_orders

  resources :vendor_role_types

  resources :vendor_roles

  resources :time_schedules

  resources :seqs

  resources :resultcodes

  resources :requests

  resources :proxy_interfaces

  resources :procedure_measurements

  resources :procedures

  resources :phones

  resources :packages_vendor_role_types

  resources :packages

  resources :other_contactinfos

  resources :organization_names

  resources :organizations

  resources :objectrefs

  resources :nametypes

  resources :name_type_authorities

  resources :measurements

  resources :material_item_names

  resources :material_items

  resources :interfaces

  resources :hazards

  resources :eprilogs

  resources :emails

  resources :districts

  resources :crew_names

  resources :crews

  resources :contactperson_phones

  resources :contactperson_other_contactinfos

  resources :contactperson_emails

  resources :contactperson_addresses

  resources :contactpeople

  resources :comments

  resources :attachments

  resources :asset_procedures

  resources :asset_names

  resources :assets

  resources :address_position_points

  resources :address_hazards

  resources :address_districts

  resources :addresses

  get "home/index"
  get "home/acceptTerms"
  get "home/hideWorkHelp"
  root :to => "home#splash"

  
  

end

ui/app/models/address.rb
class Address < ActiveRecord::Base

   self.table_name = "address"

  has_and_belongs_to_many  :contactpeople, join_table: "contactperson_addresses"

end

ui/app/models/address_district.rb
class AddressDistrict < ActiveRecord::Base
  belongs_to :address
  belongs_to :district
end

ui/app/models/asset.rb
class Asset < ActiveRecord::Base
  self.table_name = "asset"

  belongs_to :address

  has_and_belongs_to_many  :work_tasks, join_table: "work_task_assets"
  has_and_belongs_to_many  :crews, join_table: "crew_assets"
  has_and_belongs_to_many  :proceds, join_table: "asset_proceds"
  
  has_many   :asset_names


end

ui/app/models/asset_name.rb
class AssetName < ActiveRecord::Base
  belongs_to :asset
  belongs_to :asset_name_type, foreign_key: "name_type_id"
end

ui/app/models/attachment.rb
class Attachment < ActiveRecord::Base

  self.table_name = "attachment"

  has_and_belongs_to_many  :work_orders, join_table: "work_order_attachments"

  # Attachment.inheritance_column
  # http://apidock.com/rails/ActiveRecord/Base/inheritance_column/class
  self.inheritance_column = 'none'
  def attachment
    nil
  end

  def poster_filename
    "#{filename}"
  end

end

ui/app/models/comment.rb
class Comment < ActiveRecord::Base

  self.table_name = "comment"

  has_and_belongs_to_many  :work_orders, join_table: "work_order_comments"
end

ui/app/models/crew.rb
class Crew < ActiveRecord::Base

  self.table_name = "crew"

  has_and_belongs_to_many  :work_tasks, join_table: "work_task_crews"
  has_many :crew_names
  has_and_belongs_to_many  :assets, join_table: "crew_assets"


end

ui/app/models/crew_name.rb
class CrewName < ActiveRecord::Base
  self.table_name = "crew_names"

  belongs_to :crew
  belongs_to :crew_name_type, foreign_key:  "name_type_id"

end

ui/app/models/district.rb
class District < ActiveRecord::Base
end

ui/app/models/email.rb
class Email < ActiveRecord::Base

 self.table_name = "email"

 has_and_belongs_to_many  :contactperson, join_table: "contactperson_emails"

end

ui/app/models/eprilog.rb
class Eprilog < ActiveRecord::Base
end

ui/app/models/hazard.rb
class Hazard < ActiveRecord::Base

  self.table_name = "hazards"

  has_and_belongs_to_many  :work_orders, join_table: "work_order_hazards"

end

ui/app/models/interface.rb
class Interface < ActiveRecord::Base
  belongs_to :package
  belongs_to :vendor_role_type
end

ui/app/models/nametype.rb
class Nametype < ActiveRecord::Base

  self.table_name = "nametype"


  belongs_to :name_type_authority
end

ui/app/models/objectref.rb
class Objectref < ActiveRecord::Base
end

ui/app/models/package.rb
class Package < ActiveRecord::Base
end

ui/app/models/phone.rb
class Phone < ActiveRecord::Base

  self.table_name = "phone"


 has_and_belongs_to_many  :contactperson, join_table: "contactperson_phones"

end

ui/app/models/proced.rb
class Proced < ActiveRecord::Base
   self.table_name = "proced"

  has_and_belongs_to_many  :assets, join_table: "asset_proceds"
  has_and_belongs_to_many  :measurements, join_table: "proced_measurements"


end

ui/app/models/request.rb
class Request < ActiveRecord::Base
end

ui/app/models/seq.rb
class Seq < ActiveRecord::Base
end

ui/app/models/work_task.rb
class WorkTask < ActiveRecord::Base
  self.table_name = "work_task"

  belongs_to :asset, class_name: "Asset", foreign_key: "old_asset_id"

  has_many :work_task_names
  has_and_belongs_to_many  :work_orders, join_table: "work_order_work_tasks"
  has_and_belongs_to_many  :time_schedules, join_table: "work_task_time_schedules"
  has_and_belongs_to_many  :assets, join_table: "work_task_assets"

  has_and_belongs_to_many  :crews, join_table: "work_task_crews"


end

ui/app/controllers/address_districts_controller.rb
class AddressDistrictsController < ApplicationController
  before_action :set_address_district, only: [:show, :edit, :update, :destroy]

  # GET /address_districts
  # GET /address_districts.json
  def index
    @address_districts = AddressDistrict.all
  end

  # GET /address_districts/1
  # GET /address_districts/1.json
  def show
  end

  # GET /address_districts/new
  def new
    @address_district = AddressDistrict.new
  end

  # GET /address_districts/1/edit
  def edit
  end

  # POST /address_districts
  # POST /address_districts.json
  def create
    @address_district = AddressDistrict.new(address_district_params)

    respond_to do |format|
      if @address_district.save
        format.html { redirect_to @address_district, notice: 'Address district was successfully created.' }
        format.json { render :show, status: :created, location: @address_district }
      else
        format.html { render :new }
        format.json { render json: @address_district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /address_districts/1
  # PATCH/PUT /address_districts/1.json
  def update
    respond_to do |format|
      if @address_district.update(address_district_params)
        format.html { redirect_to @address_district, notice: 'Address district was successfully updated.' }
        format.json { render :show, status: :ok, location: @address_district }
      else
        format.html { render :edit }
        format.json { render json: @address_district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /address_districts/1
  # DELETE /address_districts/1.json
  def destroy
    @address_district.destroy
    respond_to do |format|
      format.html { redirect_to address_districts_url, notice: 'Address district was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address_district
      @address_district = AddressDistrict.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_district_params
      params.require(:address_district).permit(:address_id, :district_id)
    end
end

ui/app/helpers/address_districts_helper.rb
module AddressDistrictsHelper
end

ui/app/views/address_districts/_form.html.erb
<%= form_for(@address_district) do |f| %>
  <% if @address_district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address_district.errors.count, "error") %> prohibited this address_district from being saved:</h2>

      <ul>
      <% @address_district.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address_id %><br>
    <%= f.text_field :address_id %>
  </div>
  <div class="field">
    <%= f.label :district_id %><br>
    <%= f.text_field :district_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ui/app/views/address_districts/edit.html.erb
<h1>Editing address_district</h1>

<%= render 'form' %>

<%= link_to 'Show', @address_district %> |
<%= link_to 'Back', address_districts_path %>

ui/app/views/address_districts/index.html.erb
<h1>Listing address_districts</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>District</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @address_districts.each do |address_district| %>
      <tr>
        <td><%= address_district.address %></td>
        <td><%= address_district.district %></td>
        <td><%= link_to 'Show', address_district %></td>
        <td><%= link_to 'Edit', edit_address_district_path(address_district) %></td>
        <td><%= link_to 'Destroy', address_district, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address district', new_address_district_path %>

ui/app/views/address_districts/new.html.erb
<h1>New address_district</h1>

<%= render 'form' %>

<%= link_to 'Back', address_districts_path %>

ui/app/views/address_districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @address_district.address %>
</p>

<p>
  <strong>District:</strong>
  <%= @address_district.district %>
</p>

<%= link_to 'Edit', edit_address_district_path(@address_district) %> |
<%= link_to 'Back', address_districts_path %>